Repository team-dudoji/dudoji-android, pull requests merged in 2025-02, with the labels that each got.

#13 Feature/issue 11
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dudoji/android/LogCountService.kt
  app/src/main/java/com/dudoji/android/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: feature

#17 Feature/issue 9
  app/build.gradle.kts
  app/src/androidTest/java/com/dudoji/android/model/mapsection/BitmapTester.kt
  app/src/androidTest/java/com/dudoji/android/util/mapsection/MapSectionParsreTester.kt
  app/src/main/java/com/dudoji/android/map/MapActivity.kt
  app/src/main/java/com/dudoji/android/model/mapsection/Bitmap.kt
  app/src/main/java/com/dudoji/android/model/mapsection/DetailedMapSection.kt
  app/src/main/java/com/dudoji/android/model/mapsection/MapSection.kt
  app/src/main/java/com/dudoji/android/util/base64/Base64Decoder.kt
  app/src/main/java/com/dudoji/android/util/mapsection/MapSectionParser.kt
  app/src/main/java/com/dudoji/android/util/tile/MaskTileProvider.kt
  app/src/main/java/com/dudoji/android/util/tile/mask/IMaskTileMaker.kt
  app/src/main/java/com/dudoji/android/util/tile/mask/OpaqueMaskTileMaker.kt
  app/src/main/res/raw/map_section_response_test_data.json
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
Labels: feature

#21 Feature/issue 16
  app/src/main/java/com/dudoji/android/map/MapActivity.kt
  app/src/main/java/com/dudoji/android/model/mapsection/Bitmap.kt
  app/src/main/java/com/dudoji/android/model/mapsection/DetailedMapSection.kt
  app/src/main/java/com/dudoji/android/model/mapsection/MapSection.kt
  app/src/main/java/com/dudoji/android/model/mapsection/MapSectionManager.kt
  app/src/main/java/com/dudoji/android/model/mapsection/MapSectionProcessor.kt
  app/src/main/java/com/dudoji/android/util/base64/Base64Decoder.kt
  app/src/main/java/com/dudoji/android/util/mapsection/BitmapUtil.kt
  app/src/main/java/com/dudoji/android/util/mapsection/MapSectionParser.kt
  app/src/main/java/com/dudoji/android/util/tile/MaskTileProvider.kt
  app/src/main/java/com/dudoji/android/util/tile/TilePositionUtil.kt
  app/src/main/java/com/dudoji/android/util/tile/mask/IMaskTileMaker.kt
  app/src/main/java/com/dudoji/android/util/tile/mask/MapSectionMaskTileMaker.kt
  app/src/main/java/com/dudoji/android/util/tile/mask/OpaqueMaskTileMaker.kt
  app/src/main/res/raw/map_section_response_test_data.json
Labels: feature

#20 Origin/feature/issue 18
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dudoji/android/MainActivity.kt
  app/src/main/java/com/dudoji/android/map/MapActivity.kt
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_map.xml
  app/src/main/res/drawable/menu_click_color.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/menu/navi_menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feature

#24 Origin/feature/issue 23
  app/src/main/java/com/dudoji/android/MainActivity.kt
  app/src/main/java/com/dudoji/android/NavigatableActivity.kt
  app/src/main/java/com/dudoji/android/map/MapActivity.kt
Labels: fix

#27 Feature/issue 22
  app/src/main/java/com/dudoji/android/map/MapActivity.kt
  app/src/main/java/com/dudoji/android/model/mapsection/Bitmap.kt
  app/src/main/java/com/dudoji/android/model/mapsection/MapSection.kt
  app/src/main/java/com/dudoji/android/util/tile/TileCoordinateUtil.kt
  app/src/main/java/com/dudoji/android/util/tile/mask/PositionsMaskTileMaker.kt
Labels: feature

#26 Feature/issue 25
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dudoji/android/LogCountService.kt
  app/src/main/java/com/dudoji/android/MainActivity.kt
  app/src/main/java/com/dudoji/android/location/LocationActivity.kt
  app/src/main/java/com/dudoji/android/location/LocationRepository.kt
  app/src/main/java/com/dudoji/android/location/LocationService.kt
  app/src/main/java/com/dudoji/android/map/MapActivity.kt
  app/src/main/java/com/dudoji/android/util/PermissionUtil.kt
  app/src/main/res/drawable/ic_location.xml
  app/src/main/res/layout/activity_location.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/navi_menu.xml
Labels: feature

#29 Feature/issue 28
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dudoji/android/location/LocationActivity.kt
  app/src/main/java/com/dudoji/android/location/LocationRepository.kt
  app/src/main/java/com/dudoji/android/location/LocationService.kt
  app/src/main/java/com/dudoji/android/repository/RevealCircleRepository.kt
  app/src/main/java/com/dudoji/android/util/NetWorkUtil.kt
  app/src/main/res/layout/activity_location.xml
  app/src/main/res/xml/network_security_config.xml
Labels: feature

#31 Refactoring/issue 30
  app/src/androidTest/java/com/dudoji/android/model/mapsection/BitmapTester.kt
  app/src/main/java/com/dudoji/android/MainActivity.kt
  app/src/main/java/com/dudoji/android/location/LocationActivity.kt
  app/src/main/java/com/dudoji/android/map/MapActivity.kt
  app/src/main/java/com/dudoji/android/model/MapSectionManager.kt
  app/src/main/java/com/dudoji/android/model/RevealCircle.kt
  app/src/main/java/com/dudoji/android/model/mapsection/Bitmap.kt
  app/src/main/java/com/dudoji/android/model/mapsection/MapSectionProcessor.kt
  app/src/main/java/com/dudoji/android/repository/RevealCircleRepository.kt
  app/src/main/java/com/dudoji/android/util/listener/IListener.kt
  app/src/main/java/com/dudoji/android/util/listener/ListenerCaller.kt
  app/src/main/java/com/dudoji/android/util/location/IRevealCircleListener.kt
  app/src/main/java/com/dudoji/android/util/location/LocationService.kt
  app/src/main/java/com/dudoji/android/util/tile/TileCoordinateUtil.kt
  app/src/main/java/com/dudoji/android/util/tile/mask/MapSectionMaskTileMaker.kt
  app/src/main/java/com/dudoji/android/util/tile/mask/PositionsMaskTileMaker.kt
Labels: refactoring

#33 Feature/issue 32
  app/src/main/java/com/dudoji/android/util/MapUtil.kt
Labels: feature
